### ISSUE TITLE
User Data Seed sets incorrect password hash

### ISSUE THREAD

**Issue by tbd-develop** [tbd-friends/PetHome#16]
On a fresh DB, the hasData in the migration will update the user in the DB with the hardcoded password

**Comment by canhorn** [comment]
**Replication Step:**
1. Clear out the Database for PetHome-Dev, be that dropping it or removing it from docker
    a. DROP DATABASE [PetHome-Dev]
    b. docker rm -f global_sql_server
2. Verify that the Database is no longer in your SQL Server or the sql server is no long in docker
    a. USE [PetHome-Dev]
        1. Should see Database 'PetHome-Dev' does not exist.
    b. docker ps -a
    1. Should not contain listing for global_sql_server
3. If you run the docker steps recreate the docker container from the steps in the wiki
    a. https://github.com/tbd-friends/PetHome/wiki/Project's-Docker-Usage
4. Run Database Migrations
    a. Follow steps provided by the root readme
        1. https://github.com/tbd-friends/PetHome/blob/d011c5c232df19d318ed49bb5e70c43faed3dccb/README.md
5. Check for PasswordHash of hardcoded migration
    a. Invalid: AQAAAAEAACcQAAAAEIVDPe+D2k9DYm8aaZlygE1ycvP2BRWCG5m/08oxAWV/yXRq84CDZIl+GZQBVp7rTA==
    
**More Details:**
When running the migrations on a fresh database, the creation of the admin user "manager@pethome.app" will use the default migration data in the 
https://github.com/tbd-friends/PetHome/blob/d011c5c232df19d318ed49bb5e70c43faed3dccb/src/view/Data/Migrations/20190829030130_SeedInitialUser.cs

File that should take precedent over the creation of the user and the password:
https://github.com/tbd-friends/PetHome/blob/d011c5c232df19d318ed49bb5e70c43faed3dccb/src/view/Data/Configurations/AppUserEntityConfiguration.cs

**Comment by tbd-develop** [comment]
Our initial discussion around this involved using a static class of some form rather than using the migration to seed the user. 

- Could we replace the migration with the static class
- Still seed the user with migration, but when starting up if the user password hash matches the known hash, reset it? (that doesn't feel like a nice solution to me) 

Any thoughts?

**Comment by canhorn** [comment]
Since we might want this to self-healing as well, say some process deletes the admin user, we could look at baking the process to add the admin in Startup. 
So when running this process it will check if the user exists, then either add them back with the password provided or ignore the processing.
I am pretty sure @Junicus had this type of process in place already, as a startup flag, but just deploying the application and checking could ease complexity. 
We also get the added benefit of being right in the DI pipeline.

We could use an IApplicationBuilder extension method to encapsulate this logic out of Startup.

One down side is that the first every startup of the app will incur the cost to query and create the admin, but after it will just be a query to see if the admin exists.

**Comment by Junicus** [comment]
Well more than when the migration happens I would say is using the UserManager class, as creating users is one of it's purposes.  I think that with the seeding in migration we managed to get DI working, so we could resolve an UserManager there and let it handle that process, for sure know that either in startup or in a static class works.  The pattern that I had implemented is just checking for an argument for the app, much faster, less work than querying the database on every startup, also you might want the default account gone, so that is also legit.  Having it check on startup and create it if not there might not be as nice as it being part of an intended user input.

**Comment by theancientcoder** [comment]
We can change the implementation & explore other options as suggested above or alternative solution would be to simply leave the "Seed Initial User" migration to be added following checkout and after setting the password.  For this we will need to add a single line to the instructions  on getting started guide. 

> dotnet ef migrations add SeedInitialUser --context IdentityContext
